env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "import/no-named-as-default": 0,
  "import/no-named-as-default-member": 0,
  "react/jsx-props-no-spreading": 0,
  "react/function-component-definition": [
      2,
    {
      namedComponents: "arrow-function",
      unnamedComponents: "arrow-function",
    },
  ],
}
settings: {
  'import/resolver': {
    node: {
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
      moduleDirectory: ['node_modules', 'src/'],
    },
  },
}